### ISSUE TITLE
Installing Message Board

### ISSUE THREAD

**Issue by rlogical-techsoft** [micheleangioni/message-board#2]
Hello Michele Angioni,

I am trying to install your laravel message board package to my project.

I gone through following steps:

I install fresh laravel 5.2.*.

Install your package successfully.

But after installation I going through you installation guide but stuck with it.

When I am trying to run this command : **php artisan vendor:publish** it will show **Nothing to publish for tag [].** and it's not created **ma_messageboard.php** file in **config/app.php**

Is am I missing something ?

Can you please help me out,

Thanks,

**Comment by micheleangioni** [comment]
Hi @rlogical-techsoft ,

yeah you are right, by launching `php artisan vendor:publish` on a fresh Laravel installation I receive that error too.

However it seems to be something Laravel-related, since clearing the cached config files by using `php artisan config:clear` and then trying again `php artisan vendor:publish` it works. At least for me.

Probably now `php artisan optimize` (that's launched after each `composer install` or `composer update`, see Laravel composer.json) also caches the config files.

Take also a look [here](http://stackoverflow.com/questions/32090564/vendorpublish-nothing-to-publish-for-tag-only-on-production-server).

Please let me know if you manage to solve the problem, I leave the issue open.

Michele

**Comment by rlogical-techsoft** [comment]
Thanks for reply, 

Solved the issue, but I am stuck with your package, I don't understand from where I have to start.

If possible then please provide the demo code so it would be very big help for me and other developers who looking for this kind of package.

Thanks again,

**Comment by micheleangioni** [comment]
@rlogical-techsoft I'm happy you solved the issue.
About the demo code, it isn't something I can work immediatly. I leave #1 open and I'll post updates there.

However, just to give a start, follow the following steps
1. Install the package, publish the config, run the migrations
2. Set you User model in the ma_messageboard.php config file (see [here](https://github.com/micheleangioni/message-board/wiki/Configuration))
3. Add the `MicheleAngioni\MessageBoard\MbTrait` trait to your User model
4. Implement the `MicheleAngioni\MessageBoard\Contracts\MbUserInterface` interface into your User model
5. Into a Controller of your choice add the following code

``` php
$user = Auth::user();
MessageBoard::createPost($user, null, null, 'My First Post');
```

where the first line uses the Auth facade to retrieve the authenticated user while the second line uses the MessageBoard facade to create a Post in the User Message Board.
